name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile.2019'
      - 'Dockerfile.2023'
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image 2019
      run: docker build . --file Dockerfile.2019 --tag ghcr.io/ximeraproject/xake2019:latest
    - name: Build the Docker image 2023
      run: docker build . --file Dockerfile.2023 --tag ghcr.io/ximeraproject/xake2023:latest

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
     
    - name: Push xake2019:latest
      run: docker push ghcr.io/ximeraproject/xake2019:latest
    - name: Push xake2023:latest
      run: docker push ghcr.io/ximeraproject/xake2023:latest
     
